display_name: FlClash

packager: LM-Firefly
packagerEmail: firefly.lzh@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

group: Applications/Internet

startup_notify: true
