name: Update submodule

on:
  repository_dispatch:
    types:
      - core-updated
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # 自动取消其他运行中的workflow
  cancel-in-progress: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{secrets.ACTIONS_TOKEN}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Checkout and Update submodules
        run: git submodule update --init --recursive --remote --force

      - name: Update Clash.Meta
        run: |
          sudo rm -rf core/Clash.Meta
          git clone -b FlClash https://github.com/LM-Firefly/Clash.Meta.git
          mv Clash.Meta core/Clash.Meta

      - name: Update flutter_distributor
        run: |
          sudo rm -rf plugins/flutter_distributor
          git clone -b FlClash https://github.com/chen08209/flutter_distributor.git
          mv flutter_distributor plugins/flutter_distributor

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install update-go-mod-replace
        run: |
          go install github.com/metacubex/update-go-mod-replace@latest

      - name: Update Gomod
        run: |
          cd ${{ github.workspace }}/core/
          update-go-mod-replace ${{ github.workspace }}/core/Clash.Meta/go.mod $(pwd)/go.mod
          go mod tidy

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
#          token: ${{ steps.generate-token.outputs.token }}
          token: ${{env.GIT_TOKEN}}
          commit-message: Update Dependencies
          branch: update-dependencies
          delete-branch: true
          title: 'Update Dependencies'
          draft: false
          body: |
            - Update Clash.Meta Core
            - Update Dependecies
          labels: |
            Update

      - name: PR result
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
